import { Episode } from "./interfaces/episode";

const Episodes: Episode[] = [
	{
		season: 1,
		episode: 1,
		title: "Dio the Invader",
		titleJP: "侵略者ディオ",
		titleJPRomaji: "Shinryakusha Dio",
		description: "Englishman George Joestar mistakenly assumes Dario Brando had saved his life during a carriage accident, and decides to adopt his son, Dio. Heir to the Joestar Estate, Jonathan Joestar, attempts to befriend Dio, but Dio's plan from the start is to drive JoJo to madness and earn George's trust so that he can become the heir to the Joestar fortune. Dio violently beats JoJo in a boxing match, turns his friends against him, steals his girlfriend Erina's first kiss, and even burns his dog Danny to death in an incinerator.",
		originalAirDate: "October 5, 2012",
		englishAirDate: "October 5, 2012",
		url: "https://www.crunchyroll.com/jojos-bizarre-adventure/episode-1-dio-the-invader-652081",
	},
	{
		season: 1,
		episode: 2,
		title: "A Letter from the Past",
		titleJP: "過去からの手紙",
		titleJPRomaji: "Kako kara no Tegami",
		description: "Seven years have passed since Dio came to the Joestar mansion. George is shown to be sick in bed. At first, it was thought to be a common cold, but it seems to be getting worse. Jonathan learns that Dio killed his father, Dario, and he is trying to use the same poison to kill George.After confronting Dio, Jonathan goes to London searching for the origin of the poison not knowing what awaits him there.",
		originalAirDate: "October 12, 2012",
		englishAirDate: "October 12, 2012",
		url: "https://www.crunchyroll.com/jojos-bizarre-adventure/episode-2-a-letter-from-the-past-652083",
	},
	{
		season: 1,
		episode: 3,
		title: "Youth with Dio",
		titleJP: "ディオとの青春",
		titleJPRomaji: "Dio to no Seishun",
		description: "Having found an antidote and given it to his father, JoJo prepares to turn Dio in to the police. Dio tries to get JoJo's guard down by saying he will turn himself in, but Speedwagon, who has followed JoJo from London, sees through Dio's lies, presenting the druggist who sold Dio the poison, whilst George reveals that he has heard everything. As JoJo attempts to handcuff Dio, Dio attempts to stab him, only to stab George who got in the way to protect JoJo. With George's blood, he activates the stone mask on himself before the police shoot him. Before George passes away, he tells his son not to blame Dio, saying it was his fault for not being able to see through Dio's earlier treachery and apologizes for having been too harsh for his son. Just then, Dio comes back to life as a vampire, proving invincible to firearms and draining the blood of one of the cops. As JoJo prepares to fight Dio, believing he can defeat him by destroying his brain, the cop reanimates as a zombie, though JoJo manages to kill it quickly. As several attempts to kill Dio fail, JoJo sets the mansion ablaze and leads Dio to the roof so Speedwagon can escape. JoJo attempts to kill Dio with a suicide attack, dragging him into the flames of the mansion with him and manages to use the mansion's layout to both land safely and impale Dio on a statue, assuming that he has been killed. Wang Chan later attempts to salvage the mask from the burnt ruins, but Dio's charred hand emerges and drains his blood.",
		originalAirDate: "October 19, 2012",
		englishAirDate: "October 19, 2012",
		url: "https://www.crunchyroll.com/jojos-bizarre-adventure/episode-3-youth-with-dio-652085",
	},
	{
		season: 1,
		episode: 4,
		title: "Overdrive",
		titleJP: "波紋疾走/オーバードライブ",
		titleJPRomaji: "Ōbādoraibu",
		description: "With the battle between him and Dio over, Jonathan spends the next few days with his long lost childhood romance, Erina, who had returned to tend to his injuries. While the two are out for a walk, a strange man by the name of Will Anthonio Zeppeli appears and heals Jonathan's broken arm. He warns Jonathan that Dio is still alive and the only way to defeat him and the Stone Mask is through an old fighting technique known as the \"Ripple.\" Zeppeli spends the next few days training Jonathan and soon after Jonathan, Zeppeli as well as Speedwagon set off on their journey to the town of Windknight's Lot, where Dio lies. On the road there, the group encounters Jack the Ripper, who has been turned into a zombie and a faithful servant of Dio. With Zeppeli's help, Jonathan manages to learn the secret of the Ripple Overdrive.",
		originalAirDate: "October 26, 2012",
		englishAirDate: "October 26, 2012",
		url: "https://www.crunchyroll.com/jojos-bizarre-adventure/episode-4-overdrive-652087",
	},
	{
		season: 1,
		episode: 5,
		title: "The Dark Knights",
		titleJP: "暗黒の騎士達",
		titleJPRomaji: "Ankoku no Kishitachi",
		description: "On the way to Windknights Lot, Jonathan's group encounters a kid by the name of Poco, who attempts to steal their luggage. Poco is easily captured, but they soon realize that he was under hypnosis, and was simply bait to lure them into a graveyard. As night falls, they are greeted by none other than Dio who had healed most of his injuries since the mansion battle. At first, Dio, using his newly found vampire powers, summons several zombies, but they are easily defeated by Zeppeli and Jonathan via the Ripple. Zeppeli attempts to release an overdrive on Dio, but Dio grabs hold of his hand and then use his ability to lower his body temperature and freezes his own hand, along with Zeppeli's. With the blood frozen in his arm, Zeppeli is unable to use the Ripple and is severely injured. Jonathan attempts a quick defense, but both he and Zeppeli are easily defeated. Dio decides that it is pointless for him to fight and summons the two undead legendary Dark Knights, Tarkus and Bruford. Dio allows Bruford to solo Jonathan and the two commence their battle.",
		originalAirDate: "November 2, 2012",
		englishAirDate: "November 2, 2012",
		url: "https://www.crunchyroll.com/jojos-bizarre-adventure/episode-5-the-dark-knights-652089",
	},
	{
		season: 1,
		episode: 6,
		title: "Tomorrow's Courage",
		titleJP: "(あしたの勇気)",
		titleJPRomaji: "Ashita no Yūki",
		description: "After having barely managed to avoid JoJo's underwater overdrive, Bruford ensnares JoJo with his hair once more. However, JoJo manages to block Bruford's attack and channels an overdrive through a kick into Bruford's sword, which causes one of his arms to disintegrate. From here, Jonathan is able to escape, and unleashes a Sunlight Yellow Overdrive barrage against him. As Bruford's body starts to disintegrate, he regains his human soul, feeling at peace and leaving JoJo his sword before completely disintegrating. Tarkus then attacks, but JoJo and Zeppeli manage to get Speedwagon and Poco to safety using a bunch of leaves as a hang glider. As they make their escape, Zeppeli recalls how he learned to control the Ripple from a man named Tonpetty. Tarkus leaps after them, causing them to touch down at a knight's training ground in order to stand against him. Tarkus manages to crash into one of the outer walls and enters the training grounds first. JoJo is pulled inside the grounds, thrusting him into a Chain Neck Deathmatch, in which one must decapitate the other in order to free himself. Realizing JoJo will be killed if no one does anything, Poco overcomes his nerves and enters the grounds via a window, managing to unlock the door so Zeppeli can get inside.",
		originalAirDate: "November 9, 2012",
		englishAirDate: "November 9, 2012",
		url: "https://www.crunchyroll.com/jojos-bizarre-adventure/episode-6-tomorrows-courage-652091",
	},
	{
		season: 1,
		episode: 7,
		title: "Sorrowful Successor",
		titleJP: "うけ継ぐ者",
		titleJPRomaji: "Uketsugumono",
		description: "Zeppeli recalls how Tonpetty foretold where his death would take place;The description fits with the very place he is at that moment. Knowing this, Zeppeli fights against Tarkus with the intention of finding a way to free JoJo. However, Tarkus ensnares him with a chain and rips his body into two. Using the last of his strength, Zeppeli transfers the last of his Ripple energy to Jonathan, allowing him to heal his injuries, break free from his chains, and defeat Tarkus easily. Following the battle, Zeppeli tells JoJo that he has accepted his fate and has passed his will onto him before passing away. As JoJo, Speedwagon, and Poco make their way back to Windknights Lot, they encounter Mr. Adams, one of the villagers who at first reacts friendly to their arrival, but his urge for blood reveals his true nature as a zombie. He attacks Poco with his tongue, but Jonathan defeats him easily by taking his tongue and stomping on his face using the Ripple. A moment later, a stranger attacks Jonathan with a kick that restraints both his arms. Jonathan, surprised at first, manages to evade by counterattacking with a headbutt. Before the battle continues, the stranger confesses that he is a human and only wanted to test Jonathan's power. He introduces himself as Dire, one of Zeppeli's Friend and a Ripple User. Straizo, another student, makes his entry and shortly after him, Master Tonpetty. Along with his students, he joins JoJo on his journey. Meanwhile, it is revealed that Poco's sister has been kidnapped by Dio.",
		originalAirDate: "November 16, 2012",
		englishAirDate: "November 16, 2012",
		url: "https://www.crunchyroll.com/jojos-bizarre-adventure/episode-7-sorrowful-successor-652093",
	},
	{
		season: 1,
		episode: 8,
		title: "Bloody Battle! JoJo & Dio",
		titleJP: "血戦! JOJO & DIO",
		titleJPRomaji: "Kessen! JoJo & Dio",
		description: "After defeating the monster Doobie and saving Poco's sister, Jonathan climbs the stairs and reaches the final room where Dio awaits. Jonathan challenges Dio to one final match to avenge the death of his friends. However, Dire pushes Jonathan out of way and challenges Dio himself but is killed after Dio freezes his legs and shatters him. Dire's head manages to survive and launches a Ripple infused rose, impaling Dio in his right eye. This gives Jonathan an idea; in order to combat Dio's freezing by contact technique, Jonathan infuses the sword he had received earlier, Luck & Pluck, with the Ripple. As the battle begins, Jonathan cuts Dio's arm off and slices him in half. Dio manages to break Luck & Pluck after freezing Jonathan's arm and the two unleash one final attack at each other. Jonathan's double fist overdrive succeeds and Dio falls off the ledge and slowly melts away.",
		originalAirDate: "November 23, 2012",
		englishAirDate: "November 23, 2012",
		url: "https://www.crunchyroll.com/jojos-bizarre-adventure/episode-8-bloody-battle-jojo-dio-652095",
	},
	{
		season: 1,
		episode: 9,
		title: "The Final Ripple!",
		titleJP: "最後の波紋！",
		titleJPRomaji: "Saigo no Hamon!",
		description: "As Dio falls following his battle with JoJo, he decapitates himself before the Ripple reaches his head, which is recovered by his zombie servant Wang Chung. Meanwhile, with the Stone Mask destroyed, JoJo marries Erina and they head off on a honeymoon to America on a cruise across the Atlantic Ocean. As JoJo and Erina enjoy their cruise, JoJo discovers that Wang Chung has snuck aboard, meaning Dio is still alive. As JoJo comes face to face with Dio, who wants his body to replace his own, Erina arrives on the scene just as JoJo receives a near-fatal attack to his neck. Meanwhile, the ship starts to run amok with zombies after Wang Chung spreads the infection. Using the last Ripple energy he has, JoJo manages to decapitate Wang Chung, making his body obstruct a piece of the cruise ship's mechanism, setting the ship on a path to explosion. As Erina resolves to die by JoJo's side, JoJo tells her to live on so she can protect a baby whose mother was killed. As the ship starts to explode, Dio makes a last ditch attempt to take JoJo's body, but JoJo stops him, passing away with Dio's head in his arms whilst Erina and the baby hide in Dio's bomb-proof coffin to protect them from the explosion. Erina is eventually rescued near the Canary Islands a day later, and vows to pass on the truth of what happened on that night, 8 February 1888, through the generations, starting with the child she conceived with JoJo before his untimely death.",
		originalAirDate: "November 23, 2012",
		englishAirDate: "November 23, 2012",
		url: "https://www.crunchyroll.com/jojos-bizarre-adventure/episode-9-the-final-ripple-652097",
	},



];

export default Episodes;