import { Episode } from "./interfaces/episode";

const Episodes: Episode[] = [
	{
		season: 1,
		episode: 1,
		title: "Dio the Invader",
		titleJP: "侵略者ディオ",
		titleJPRomaji: "Shinryakusha Dio",
		description: "Englishman George Joestar mistakenly assumes Dario Brando had saved his life during a carriage accident, and decides to adopt his son, Dio. Heir to the Joestar Estate, Jonathan Joestar, attempts to befriend Dio, but Dio's plan from the start is to drive JoJo to madness and earn George's trust so that he can become the heir to the Joestar fortune. Dio violently beats JoJo in a boxing match, turns his friends against him, steals his girlfriend Erina's first kiss, and even burns his dog Danny to death in an incinerator.",
		originalAirDate: "October 5, 2012",
		englishAirDate: "October 5, 2012",
		url: "https://www.crunchyroll.com/jojos-bizarre-adventure/episode-1-dio-the-invader-652081",
	},
	{
		season: 1,
		episode: 2,
		title: "A Letter from the Past",
		titleJP: "過去からの手紙",
		titleJPRomaji: "Kako kara no Tegami",
		description: "Seven years have passed since Dio came to the Joestar mansion. George is shown to be sick in bed. At first, it was thought to be a common cold, but it seems to be getting worse. Jonathan learns that Dio killed his father, Dario, and he is trying to use the same poison to kill George.After confronting Dio, Jonathan goes to London searching for the origin of the poison not knowing what awaits him there.",
		originalAirDate: "October 12, 2012",
		englishAirDate: "October 12, 2012",
		url: "https://www.crunchyroll.com/jojos-bizarre-adventure/episode-2-a-letter-from-the-past-652083",
	},
	{
		season: 1,
		episode: 3,
		title: "Youth with Dio",
		titleJP: "ディオとの青春",
		titleJPRomaji: "Dio to no Seishun",
		description: "Having found an antidote and given it to his father, JoJo prepares to turn Dio in to the police. Dio tries to get JoJo's guard down by saying he will turn himself in, but Speedwagon, who has followed JoJo from London, sees through Dio's lies, presenting the druggist who sold Dio the poison, whilst George reveals that he has heard everything. As JoJo attempts to handcuff Dio, Dio attempts to stab him, only to stab George who got in the way to protect JoJo. With George's blood, he activates the stone mask on himself before the police shoot him. Before George passes away, he tells his son not to blame Dio, saying it was his fault for not being able to see through Dio's earlier treachery and apologizes for having been too harsh for his son. Just then, Dio comes back to life as a vampire, proving invincible to firearms and draining the blood of one of the cops. As JoJo prepares to fight Dio, believing he can defeat him by destroying his brain, the cop reanimates as a zombie, though JoJo manages to kill it quickly. As several attempts to kill Dio fail, JoJo sets the mansion ablaze and leads Dio to the roof so Speedwagon can escape. JoJo attempts to kill Dio with a suicide attack, dragging him into the flames of the mansion with him and manages to use the mansion's layout to both land safely and impale Dio on a statue, assuming that he has been killed. Wang Chan later attempts to salvage the mask from the burnt ruins, but Dio's charred hand emerges and drains his blood.",
		originalAirDate: "October 19, 2012",
		englishAirDate: "October 19, 2012",
		url: "https://www.crunchyroll.com/jojos-bizarre-adventure/episode-3-youth-with-dio-652085",
	},
	{
		season: 1,
		episode: 4,
		title: "Overdrive",
		titleJP: "波紋疾走/オーバードライブ",
		titleJPRomaji: "Ōbādoraibu",
		description: "With the battle between him and Dio over, Jonathan spends the next few days with his long lost childhood romance, Erina, who had returned to tend to his injuries. While the two are out for a walk, a strange man by the name of Will Anthonio Zeppeli appears and heals Jonathan's broken arm. He warns Jonathan that Dio is still alive and the only way to defeat him and the Stone Mask is through an old fighting technique known as the \"Ripple.\" Zeppeli spends the next few days training Jonathan and soon after Jonathan, Zeppeli as well as Speedwagon set off on their journey to the town of Windknight's Lot, where Dio lies. On the road there, the group encounters Jack the Ripper, who has been turned into a zombie and a faithful servant of Dio. With Zeppeli's help, Jonathan manages to learn the secret of the Ripple Overdrive.",
		originalAirDate: "October 26, 2012",
		englishAirDate: "October 26, 2012",
		url: "https://www.crunchyroll.com/jojos-bizarre-adventure/episode-4-overdrive-652087",
	},
	{
		season: 1,
		episode: 5,
		title: "The Dark Knights",
		titleJP: "暗黒の騎士達",
		titleJPRomaji: "Ankoku no Kishitachi",
		description: "On the way to Windknights Lot, Jonathan's group encounters a kid by the name of Poco, who attempts to steal their luggage. Poco is easily captured, but they soon realize that he was under hypnosis, and was simply bait to lure them into a graveyard. As night falls, they are greeted by none other than Dio who had healed most of his injuries since the mansion battle. At first, Dio, using his newly found vampire powers, summons several zombies, but they are easily defeated by Zeppeli and Jonathan via the Ripple. Zeppeli attempts to release an overdrive on Dio, but Dio grabs hold of his hand and then use his ability to lower his body temperature and freezes his own hand, along with Zeppeli's. With the blood frozen in his arm, Zeppeli is unable to use the Ripple and is severely injured. Jonathan attempts a quick defense, but both he and Zeppeli are easily defeated. Dio decides that it is pointless for him to fight and summons the two undead legendary Dark Knights, Tarkus and Bruford. Dio allows Bruford to solo Jonathan and the two commence their battle.",
		originalAirDate: "November 2, 2012",
		englishAirDate: "November 2, 2012",
		url: "https://www.crunchyroll.com/jojos-bizarre-adventure/episode-5-the-dark-knights-652089",
	},
	{
		season: 1,
		episode: 6,
		title: "Tomorrow's Courage",
		titleJP: "(あしたの勇気)",
		titleJPRomaji: "Ashita no Yūki",
		description: "After having barely managed to avoid JoJo's underwater overdrive, Bruford ensnares JoJo with his hair once more. However, JoJo manages to block Bruford's attack and channels an overdrive through a kick into Bruford's sword, which causes one of his arms to disintegrate. From here, Jonathan is able to escape, and unleashes a Sunlight Yellow Overdrive barrage against him. As Bruford's body starts to disintegrate, he regains his human soul, feeling at peace and leaving JoJo his sword before completely disintegrating. Tarkus then attacks, but JoJo and Zeppeli manage to get Speedwagon and Poco to safety using a bunch of leaves as a hang glider. As they make their escape, Zeppeli recalls how he learned to control the Ripple from a man named Tonpetty. Tarkus leaps after them, causing them to touch down at a knight's training ground in order to stand against him. Tarkus manages to crash into one of the outer walls and enters the training grounds first. JoJo is pulled inside the grounds, thrusting him into a Chain Neck Deathmatch, in which one must decapitate the other in order to free himself. Realizing JoJo will be killed if no one does anything, Poco overcomes his nerves and enters the grounds via a window, managing to unlock the door so Zeppeli can get inside.",
		originalAirDate: "November 9, 2012",
		englishAirDate: "November 9, 2012",
		url: "https://www.crunchyroll.com/jojos-bizarre-adventure/episode-6-tomorrows-courage-652091",
	},
	{
		season: 1,
		episode: 7,
		title: "Sorrowful Successor",
		titleJP: "うけ継ぐ者",
		titleJPRomaji: "Uketsugumono",
		description: "Zeppeli recalls how Tonpetty foretold where his death would take place;The description fits with the very place he is at that moment. Knowing this, Zeppeli fights against Tarkus with the intention of finding a way to free JoJo. However, Tarkus ensnares him with a chain and rips his body into two. Using the last of his strength, Zeppeli transfers the last of his Ripple energy to Jonathan, allowing him to heal his injuries, break free from his chains, and defeat Tarkus easily. Following the battle, Zeppeli tells JoJo that he has accepted his fate and has passed his will onto him before passing away. As JoJo, Speedwagon, and Poco make their way back to Windknights Lot, they encounter Mr. Adams, one of the villagers who at first reacts friendly to their arrival, but his urge for blood reveals his true nature as a zombie. He attacks Poco with his tongue, but Jonathan defeats him easily by taking his tongue and stomping on his face using the Ripple. A moment later, a stranger attacks Jonathan with a kick that restraints both his arms. Jonathan, surprised at first, manages to evade by counterattacking with a headbutt. Before the battle continues, the stranger confesses that he is a human and only wanted to test Jonathan's power. He introduces himself as Dire, one of Zeppeli's Friend and a Ripple User. Straizo, another student, makes his entry and shortly after him, Master Tonpetty. Along with his students, he joins JoJo on his journey. Meanwhile, it is revealed that Poco's sister has been kidnapped by Dio.",
		originalAirDate: "November 16, 2012",
		englishAirDate: "November 16, 2012",
		url: "https://www.crunchyroll.com/jojos-bizarre-adventure/episode-7-sorrowful-successor-652093",
	},
	{
		season: 1,
		episode: 8,
		title: "Bloody Battle! JoJo & Dio",
		titleJP: "血戦! JOJO & DIO",
		titleJPRomaji: "Kessen! JoJo & Dio",
		description: "After defeating the monster Doobie and saving Poco's sister, Jonathan climbs the stairs and reaches the final room where Dio awaits. Jonathan challenges Dio to one final match to avenge the death of his friends. However, Dire pushes Jonathan out of way and challenges Dio himself but is killed after Dio freezes his legs and shatters him. Dire's head manages to survive and launches a Ripple infused rose, impaling Dio in his right eye. This gives Jonathan an idea; in order to combat Dio's freezing by contact technique, Jonathan infuses the sword he had received earlier, Luck & Pluck, with the Ripple. As the battle begins, Jonathan cuts Dio's arm off and slices him in half. Dio manages to break Luck & Pluck after freezing Jonathan's arm and the two unleash one final attack at each other. Jonathan's double fist overdrive succeeds and Dio falls off the ledge and slowly melts away.",
		originalAirDate: "November 23, 2012",
		englishAirDate: "November 23, 2012",
		url: "https://www.crunchyroll.com/jojos-bizarre-adventure/episode-8-bloody-battle-jojo-dio-652095",
	},
	{
		season: 1,
		episode: 9,
		title: "The Final Ripple!",
		titleJP: "最後の波紋！",
		titleJPRomaji: "Saigo no Hamon!",
		description: "As Dio falls following his battle with JoJo, he decapitates himself before the Ripple reaches his head, which is recovered by his zombie servant Wang Chung. Meanwhile, with the Stone Mask destroyed, JoJo marries Erina and they head off on a honeymoon to America on a cruise across the Atlantic Ocean. As JoJo and Erina enjoy their cruise, JoJo discovers that Wang Chung has snuck aboard, meaning Dio is still alive. As JoJo comes face to face with Dio, who wants his body to replace his own, Erina arrives on the scene just as JoJo receives a near-fatal attack to his neck. Meanwhile, the ship starts to run amok with zombies after Wang Chung spreads the infection. Using the last Ripple energy he has, JoJo manages to decapitate Wang Chung, making his body obstruct a piece of the cruise ship's mechanism, setting the ship on a path to explosion. As Erina resolves to die by JoJo's side, JoJo tells her to live on so she can protect a baby whose mother was killed. As the ship starts to explode, Dio makes a last ditch attempt to take JoJo's body, but JoJo stops him, passing away with Dio's head in his arms whilst Erina and the baby hide in Dio's bomb-proof coffin to protect them from the explosion. Erina is eventually rescued near the Canary Islands a day later, and vows to pass on the truth of what happened on that night, 8 February 1888, through the generations, starting with the child she conceived with JoJo before his untimely death.",
		originalAirDate: "November 23, 2012",
		englishAirDate: "November 23, 2012",
		url: "https://www.crunchyroll.com/jojos-bizarre-adventure/episode-9-the-final-ripple-652097",
	},
	{
		season: 2,
		episode: 1,
		title: "New York's JoJo",
		titleJP: "(ニューヨークのジョジ",
		titleJPRomaji: "Nyū Yōku no JoJo",
		description: "It's been 49 years since Jonathan Joestar's death, and a much older looking Speedwagon and Straizo travel to Mexico to investigate a mysterious underground cavern. There they find it filled with similar Stone Masks to the one that was destroyed many years ago, as well a body integrated into a stone column. Meanwhile, in New York, Jonathan's grandson, Joseph Joestar (also nicknamed \"JoJo\"), saves a young African-American pick-pocket named Smokey Brown from some corrupt policemen using the Ripple. After saving him, Smokey tags along as Joseph and Erina head to a restaurant. Back in Mexico, Speedwagon is betrayed by Straizo, and presumably killed. Straizo had apparently envied the youth that the Stone Mask had granted Dio and dons one himself. After dealing with a mafia henchman at a restaurant, JoJo, Erina, and Smokey meet a mafia acquaintance of Speedwagon's who informs them that Speedwagon has been murdered by Straizo. Later that day, JoJo is confronted outside a cafe by Straizo, who had regained his youth as a vampire. Straizo plans to kill Joseph before he can unlock the full potential of the Ripple, but Joseph quickly pulls out a Tommy-Gun and promptly blasts Straizo through the cafe window.",
		originalAirDate: "December 7, 2012",
		englishAirDate: "December 7, 2012",
		url: "https://www.crunchyroll.com/jojos-bizarre-adventure/episode-10-new-yorks-jojo-652099",
	},
	{
		season: 2,
		episode: 2,
		title: "The Game Master",
		titleJP: "ゲームの達人",
		titleJPRomaji: "Gēmu no Tatsujin",
		description: "As expected, Straizo recovers from Joseph Joestar's attack and uses the same high pressurized blood laser eye attack Dio used. Joseph dodges this attack using a mirror trick prepared in advance and, manages to attack Straizo with the Ripple. Straizo absorbs it using a scarf woven from beetle muscles, but JoJo manages to sneak some grenades onto his person. Despite being blown apart, the vampire pulls himself together. Smokey asks Joseph if he has some plan, but Joseph simply says to run away and does so. Straizo catches up with them in a bridge and takes a woman hostage in order to goad JoJo into facing him. After Joseph becomes provoked, Straizo once again attacks with his Space Ripper Stingy Eyes, but JoJo manages to reflect it back at him using Ripple charged shot glasses. Joseph finishes Straits off with a punch and sends him flying off the bridge. Before he falls ,though, Joseph grabs his hand. He tries to get information out of him, but Straizo warns JoJo about a Pillar Man who will soon awaken before killing himself with his own Ripple. Meanwhile, it is revealed Speedwagon is alive and is being held captive in Mexico, where a German military general named Rudol von Stroheim interrogates him about the Pillar Man, which they have excavated from the cave and intend to revive. Meanwhile, JoJo also makes his way to Mexico, unaware that he is being followed by a strange assassin.",
		originalAirDate: "December 14, 2012",
		englishAirDate: "December 14, 2012",
		url: "https://www.crunchyroll.com/jojos-bizarre-adventure/episode-11-the-game-master-652101",
	},
	{
		season: 2,
		episode: 3,
		title: "The Pillar Man",
		titleJP: "柱の男",
		titleJPRomaji: "Hashira no Otoko",
		description: "Joseph is confronted by one of Stroheim's men, Donovan, but manages to subdue him, learning that Speedwagon is still alive in the process. He sneaks into the Nazi Base after attempting to seduce the guards by dressing as a girl. When that failed, he knocked them out and puts on their uniform. Meanwhile, Stroheim manages to awaken the Pillar Man, naming him Santana, after the winds of Mexico. To test him, Stroheim sends a vampire after Santana, which he absorbs into his body to feed itself. To Stroheim's shock, Santana manages to escape his cell by contorting his body through the air vents and launches himself into the body of one of his men. The possessed Nazi becomes bloated and begins firing bullets from his finger. Just then, Joseph, who had managed to sneak into the base, reveals himself and tears out some of Stroheim's hair. Santana emerges from the body he had taken over and begins firing more bullets from his fingers. Joseph infuses Ripple into Stroheim's hair and throws it into the air, causing them to deflect all the bullets. Joseph removes his coat and confronts Santana.",
		originalAirDate: "December 21, 2012",
		englishAirDate: "December 21, 2012",
		url: "https://www.crunchyroll.com/jojos-bizarre-adventure/episode-12-the-pillar-man-652103",
	},
	{
		season: 2,
		episode: 4,
		title: "JoJo vs. The Ultimate Life-Form",
		titleJP: "JOJO vs.究極生物",
		titleJPRomaji: "JoJo tai Kyūkyoku Seibutsu",
		description: "At first, Joseph attempts to make peace with Santana, but is instead greeted by an attack from Santana's ribs; this almost neutralizes Joseph had he not blocked the attack with his Ripple. Joseph realizes his attacks are not effective, so he feigns unconsciousness, and attacks Santana from the inside after the latter attempted to absorb him. With the Pillar Man in half, Joseph chains the upper portion and tries to drag Santana to the entrance of the base to destroy the body using the sunlight. Unfortunately, Santana grabs hold of Joseph's leg and immobilizes him just before reaching the door. Stroheim comes from behind to help, but he too is ensnared. Joseph is forced to chop Stroheim's leg off as a request allowing Stroheim to open the door. However, Santana avoids the sunlight by seeping his way into the stub where Stroheim's leg was cut off. Stroheim walks on one leg into the sunlight and pulls out a grenade. From there, he tells Joseph that the Germans had uncovered other Pillar Men in Europe and that he must go to Rome to learn how to defeat them. With that said, Stroheim ignites the grenade and destroys his own body. As a last ditch effort, Santana attacks Joseph and the two go flying into a well. Joseph reveals that the water at the bottom of the well acts as another light source due to its ability to reflect sunlight. Being hit by sunlight in two directions, Santana turns into stone and is defeated.",
		originalAirDate: "January 4, 2013",
		englishAirDate: "January 4, 2013",
		url: "https://www.crunchyroll.com/jojos-bizarre-adventure/episode-13-jojo-vs-the-ultimate-lifeform-652105",
	},
	{
		season: 2,
		episode: 5,
		title: "Ultimate Warriors from Ancient Times",
		titleJP: "太古から来た究極戦士",
		titleJPRomaji: "Taiko kara Kita Kyūkyoku Senshi",
		description: "Speedwagon brings the statued remains of Santana to the headquarters of his foundation in Washington, D.C., where it is shown he is still alive and has scientists keep his body under UV light. Realizing from Stroheim's words that there are three more powerful Pillar Men somewhere in Europe, Speedwagon takes Joseph to Rome to meet Zeppeli's grandson, Caesar, who is also skilled in using the Ripple. As Caesar questions Joseph's abilities, he fights against him using his own Ripple abilities formed from clothes filled with soapy water, encasing Joseph in a bubble, but Joseph manages to break free using a sneak attack. As Caesar makes plans for Joseph and Speedwagon to be taken to see where the Pillar Men are being kept, one of the Pillar Men, Wamuu, breaks free, killing a group of German soldiers and awakening his masters, Kars and Esidisi, a Pillar Man destroys half of Caesar's friend Mark's body simply by bumping into him as he is walking past. As Caesar is forced to use his Ripple to peacefully end Mark's suffering, he vows vengeance against the Pillar Men.",
		originalAirDate: "January 11, 2013",
		englishAirDate: "January 11, 2013",
		url: "https://www.crunchyroll.com/jojos-bizarre-adventure/episode-14-ultimate-warriors-from-ancient-times-652107",
	},
	{
		season: 2,
		episode: 6,
		title: "A Hero's Proof",
		titleJP: "ヒーローの資格",
		titleJPRomaji: "Hīrō no Shikaku",
		description: "Caesar engages Wamuu in battle for killing Mark, using his Bubble Launcher technique to surround the Pillar Man in Ripple infused bubbles. Once Wamuu realizes he is facing a Ripple user he uses his mysterious headgear to unleash a wind that bursts all of the bubbles. However, his attack is not yet over, as the movement created hundreds of miniature tornadoes that shred Caesar's skin, leaving him incapacitated and temporarily blinded in one eye. His boasts that he need not see to fight the Pillar Men amuses them, as Ripple users of two millennia past said the same things to them before they killed them. Kars and Esidisi head to the surface, allowing Wamuu to finish Caesar off as the only Ripple user left, only for Joseph to make himself known, proclaiming that he has developed his own special Ripple technique using a pair of clackers that he channels the Ripple through. Wamuu allows him to fight, slicing through his wrist to the artery to make the battle last only a minute. His first attack, the Ripple Clacker Volley, appears to miss its mark, embedding a steel ball into a pillar behind Wamuu, but this is all part of a ploy to engage his other technique, Clacker Boomerang, where he has thrown another Ripple empowered pair of clackers behind Wamuu, catching onto the original clacker, and actually landing a blow on Wamuu. Angered, Wamuu allows Joseph to continue to strike him with the clackers while he prepares his counter, the Holy Sandstorm. Wamuu claims his attack has been hindered by his eyesight and a pillar blocking Joseph, but Joseph is left barely alive. Playing dead, Joseph tries to run away, seemingly stranding Caesar and Speedwagon, but it is all a ploy to lure Wamuu away before he can kill the others. Joseph takes Wamuu on a mine cart ride through the ruins, intending to use a stick of dynamite to destroy him, but Wamuu anticipates these events and sends them flying, intending to kill Joseph for his insolence. However, Joseph proclaims that he could possibly be even stronger in a month's time, intriguing Wamuu, who decides to let Joseph live to get stronger with the Ripple in only a month, implanting a \"Wedding Ring\" in Joseph's body around his aorta that will release a deadly poison in thirty-three days' time, unless Joseph can get the antidote held in his lip piercing by killing him in battle. Esidisi, who has come to see what has been holding Wamuu up, also decides to enter in on the wager (after consuming the stick of dynamite before it explodes), implanting another poison-filled ring around Joseph's windpipe, with the antidote in his own nose piercing. Kars, however, passes on the game, and the Pillar Men leave in search of the Red Stone of Aja, and Joseph passes out from the strain of the battle. Caesar, who has been watching the whole time, realizes Joseph's resolve and promises to also get stronger with him.",
		originalAirDate: "January 18, 2013",
		englishAirDate: "January 18, 2013",
		url: "https://www.crunchyroll.com/jojos-bizarre-adventure/episode-15-a-heros-proof-652109",
	},
	{
		season: 2,
		episode: 7,
		title: "Lisa Lisa, Ripple Coach",
		titleJP: "波紋教師リサリサ",
		titleJPRomaji: "Hamon Kyoushi Risa Risa",
		description: "Wanting to teach Joseph to control his Ripple powers, Caesar takes him to Venice to meet his teacher, Lisa Lisa. Lisa Lisa orders Joseph to wear a mask that limits his breathing for the duration of his training. To start their training, Lisa Lisa tasks Joseph and Caesar to climb the Hell Climb Pillar, a 24-meter pillar covered in oil, using only the Ripple or else starve to death. Observing Caesar's efforts, Joseph learns to climb up by focusing Ripple energy in his fingertips. As the days pass as they struggle to climb, Joseph assumes there's an easy break when he spots a crack in the pillar, but this turns out to be a trap, causing the pillar to start spewing oil at high pressures from its 20-meter mark. Caesar manages to break through the barrier by using Ripple energy to simultaneously grip the pillar with his feet and repel the barrier, eventually reaching the peak. Joseph eventually manages to get past by traveling across the barrier to its weakest point so he can leap over it. As Joseph ends up running out of breath at the last meter, Caesar helps him up. As Joseph becomes pleased with the results of his training and asks for the next test, Lisa Lisa brings in her servants, Messina and Loggins, to teach them how to master the Ripple over the next few weeks.",
		originalAirDate: "January 25, 2013",
		englishAirDate: "January 25, 2013",
		url: "https://www.crunchyroll.com/jojos-bizarre-adventure/episode-16-lisa-lisa-hamon-coach-652111",
	},
	{
		season: 2,
		episode: 8,
		title: "The Deeper Plan",
		titleJP: "深く罠をはれ！",
		titleJPRomaji: "Fukaku Wana o Hare!",
		description: "Lisa Lisa explains to Joseph and Caesar how the creator of the Stone Mask, Kars, is seeking a gem known as the Red Stone of Aja to power the Stone Mask and become the ultimate life-form. Lisa Lisa reveals she herself possesses this gem which can amplify the power of the Ripple into a powerful beam, saying that it is needed to defeat the Pillar Men. With a week left until the rings inside Joseph dissolve and kill him, Lisa Lisa pits Joseph and Caesar against Loggins and Messina respectively for their final lesson. However, when Joseph reaches his destination, he finds Loggins has been killed by Esidisi. Angered, Joseph decides to confront the Pillar Man over a bed of spikes. Thanks to an intricate trap, Joseph manages to use a wire set-up on Loggins to sever Esidisi's arm. However, Esidisi manages to repair himself by taking Loggins' arm before attacking Joseph with his burning blood. Despite nearly falling for a trap himself, Joseph manages to ensnare Esidisi in conductive wool thread and hit him with the Ripple, managing to destroy him and retrieve his antidote, safely dissolving the ring around his neck. Relieved, Joseph heads back to the castle, unaware that Esidisi's brain is clinging onto his back.",
		originalAirDate: "February 1, 2013",
		englishAirDate: "February 1, 2013",
		url: "https://www.crunchyroll.com/jojos-bizarre-adventure/episode-17-the-deeper-plan-652113",
	},
	{
		season: 2,
		episode: 9,
		title: "Von Stroheim's Revenge",
		titleJP: "シュトロハイム隊の逆襲",
		titleJPRomaji: "Shutorohaimu tai no gyakushuu",
		description: "After his fight with Esidisi, Joseph heads back to the manor without realizing that Esidisi's brain had latched onto his back. Meanwhile, Lisa Lisa prepares for her bath while Suzi Q has trouble deciding on which blouse her master should wear. Suzi Q runs into Joseph downstairs, not recognizing him due to lacking the mask he'd been wearing the past few weeks. She informs Joseph that Lisa Lisa had asked to see him and advises him to wait for her to finish her bath. Suzi Q leaves and Esidisi is shown to have left Joseph's body. Joseph goes upstairs and notices Suzi Q handing off a package to a mail boat at the docks. Joseph decides to peep on Lisa Lisa bathing through the keyhole and sees Suzi Q inside, to which he expresses confusion as he had seen Suzi Q down at the docks only moments before. Lisa Lisa notices that the Red Stone of Aja is missing, and Esidisi (inside Suzi Q's body) reveals he had mailed it away in order to get it to Kars. Joseph comes in, but Esidisi intends to stall them by holding Suzi Q hostage, as in order to kill Esidisi they would have to kill her. Caesar returns and is told by Joseph and Lisa Lisa to catch the mail boat before it arrives in Venice. Esidisi attacks Caesar and blocks the doorway, preventing anyone from leaving. Joseph and Caesar used their combined Ripple to force Esidisi out of Suzi Q and neutralize any damage to her. Esidisi is disintegrated by the sunlight and Joseph admits his respect for him. Suzi Q reveals that the Stone is aboard a train headed to Switzerland and Joseph, Caesar, Lisa Lisa, and Messina drive off to catch the package before it reaches its destination. Meanwhile, Kars wonders why Esidisi had not reported back to him and assumes that something must have happened to him. A dog is nearly run over by a pair of drunk drivers, but Kars uses his Light Blades to kill them. Joseph wakes up to find that the train had been stopped by customs and that Nazi's have retrieved the package from the train, stating that they are taking it for research. A Nazi who speaks to Joseph as if he was familiar with him tells the group to talk with him in a log cabin up ahead. Later on that evening Kars approaches the cabin and senses the body heat of several soldiers inside, killing them with his Light Blades shortly afterwards. When he enters he notices that there is still one soldier left in the room, the one who addressed Joseph. Confused as to why he can't sense his body heat Kars attacks the soldier, who blocks with his hand. The soldier's glove rips from Kars' attack and reveals that it is mechanical underneath. Joseph enters the room and identifies the solider as Stroheim, much to his surprise.",
		originalAirDate: "February 8, 2013",
		englishAirDate: "February 8, 2013",
		url: "https://www.crunchyroll.com/jojos-bizarre-adventure/episode-18-von-stroheims-revenge-652115",
	},
	{
		season: 2,
		episode: 10,
		title: "A Race Toward the Brink",
		titleJP: "死の崖へつっ走れ",
		titleJPRomaji: "Shi no Gake e Tsuppashire",
		description: "Stroheim starts using his new mechanical body, which was designed to surpass Santana and to fight against Kars. However, it proves futile against Kars' blades, which cuts him down to size. As Kars attempts to retrieve the stone, Stroheim fires a beam at him, sending the stone sliding towards a cliff edge, forcing JoJo and Kars to chase after it. JoJo pulls off a trick to grab the stone, but Kars pulls him off the cliff with him. JoJo manages to save himself by using the stone as a shield and prevents his fall with help from Caesar. The next day, Caesar and the others discuss ambushing Kars' hideout before Wamuu arrives, but JoJo objects to it, believing it unwise to fight on their home turf, leading to him and Caesar getting into a fight. Feeling a sense of duty to his grandfather, Caesar decides to go alone, with Messina ordered to follow him, whilst Lisa Lisa explains to JoJo that Caesar has a secret past.",
		originalAirDate: "February 15, 2013",
		englishAirDate: "February 15, 2013",
		url: "https://www.crunchyroll.com/jojos-bizarre-adventure/episode-19-a-race-toward-the-brink-652117",
	},
	{
		season: 2,
		episode: 11,
		title: "Young Caesar",
		titleJP: "シーザー孤独の青春",
		titleJPRomaji: "Shīzā Kodoku no Seishun",
		description: "Lisa Lisa tells JoJo of Caesar's childhood, in which he took to crime at a young age after being abandoned by his debt-ridden father, Mario. However, when Caesar turned 16, Caesar came across the wall containing the Pillar Men, which was booby-trapped by Kars. Mario saved Caesar from the trap, getting absorbed into the wall, but lived long enough to tell Caesar to find Lisa Lisa and learn the Ripple. As Caesar arrives at the hotel, he is attacked by Wamuu, who is using streams of moist air to both protect him from the sunlight and reflect the light around him. Caesar launches an attack on Wamuu after he drags Messina into the hotel, but Wamuu manages to retreat inside the hotel, prompting Caesar to go in after him. Using a series of refractive bubble lenses, Caesar manages to redirect the sunlight inside the hotel to pin down Wamuu. However, Wamuu takes advantage of the split-second the sun is blotted by Caesar's attack to deliver a critical counter-attack. Too injured to continue for the fight, Caesar uses the last of his strength to steal the piercing containing the antidote for the ring around JoJo's heart. He then uses his Final Ripple to create a blood bubble to deliver the piercing and his bandana to JoJo before being crushed by the collapsing ceiling. Wamuu, finding Caesar's fight and loyalty to be admirable, allows the bubble to remain. JoJo and Lisa Lisa are attracted to the hotel after Messina does not return, and unknowingly see the light of Caesar's Final Ripple. They discover the state of the hotel, finding the bubble with the antidote and Caesar's scarf, and soon realize that Caesar has died, and weep over the loss of their friend and ally.",
		originalAirDate: "February 22, 2013",
		englishAirDate: "February 22, 2013",
		url: "https://www.crunchyroll.com/jojos-bizarre-adventure/episode-20-young-caesar-652119",
	},
	{
		season: 2,
		episode: 12,
		title: "A Hundred Against Two",
		titleJP: "100対2のかけひき",
		titleJPRomaji: "Hyaku tai Ni no Kakehiki",
		description: "Whilst following Wamuu's trail of blood, JoJo and Lisa Lisa encounter another vampire named Wired Beck, but Lisa Lisa manages to defeat him easily. As they press on, JoJo states he will not take the antidote he received until he has beaten Wamuu as a promise to Caesar. They soon arrive before Wamuu, where Kars is also waiting for them, along with a hundred vampire minions. Lisa Lisa manages to hold off their attack with a bluff saying that if both she and JoJo are killed, a time bomb will destroy the stone. Thus, she proposes that JoJo fights against Wamuu whilst she fights against Kars with the stone on the line. Wamuu and Kars arrange a place for the battle at midnight, keeping Lisa Lisa as insurance to make sure JoJo brings the stone. Whilst retrieving the stone, JoJo finds a picture of Erina from fifty years ago, becoming curious as to why Lisa Lisa would have it. Upon meeting at the arena, Lisa Lisa reveals that she was the baby that Erina rescued from the ship that fateful day, further explaining how she was raised by Straizo, who was the one who taught her about the Ripple and gave her the stone. As JoJo and Wamuu's battle is revealed to be a chariot race using vampire horses, JoJo puts on Caesar's bandanna and prepares for battle.",
		originalAirDate: "March 1, 2013",
		englishAirDate: "March 1, 2013",
		url: "https://www.crunchyroll.com/jojos-bizarre-adventure/episode-21-a-hundred-against-two-652121",
	},
	{
		season: 2,
		episode: 13,
		title: "A True Warrior",
		titleJP: "真の格闘者",
		titleJPRomaji: "Shin no Kakutōsha",
		description: "Before the match begins, it is revealed that during each lap, there will be a different weapon for whoever can grab it from a pillar first. JoJo manages to get a headstart by obstructing Wamuu's wheels with rubble, allowing him to get ahold of a sledgehammer. However, Wamuu grabs hold of the pillar itself, forcing JoJo to abandon his chariot, though JoJo manages to use the hammer to avoid getting trampled by Wamuu's horses. Wamuu launches an attack on JoJo by hiding in his horse, but JoJo manages to use his cunning to turn his sandstorm attack against him with the Ripple. In order to regain his focus, Wamuu gouges out his own eyes and grows a horn that can sense the wind in its place. As the second lap offers a pair of crossbows, JoJo ends up picking one that is too big for him to use whilst Wamuu uses the wind to guide his shots with the smaller crossbow, managing to hit JoJo's sides with a reflected shot. As he is thrown to the ground, he uses the momentum of the fall to cock his crossbow without the others noticing. JoJo appears cornered but manages to hit Wamuu with a Ripple-charged shot from his crossbow by distracting his senses with pebbles. Wamuu makes a desperate last attack by firing his severed arms at JoJo to cut off his breathing before gathering up wind for his final attack.",
		originalAirDate: "March 8, 2013",
		englishAirDate: "March 8, 2013",
		url: "https://www.crunchyroll.com/jojos-bizarre-adventure/episode-22-a-true-warrior-652123",
	},
	{
		season: 2,
		episode: 14,
		title: "The Warrior of Wind",
		titleJP: "風にかえる戦士",
		titleJPRomaji: "Kaze ni Kaeru Senshi",
		description: "Launching his Final Mode attack, Gathering Gale, which starts peeling away his own body, Wamuu begins firing a stream of wind capable of cutting stone towards Joseph. After a failed attempt at attacking him with a firebomb, Joseph strikes at Wamuu with Caesar's flaming bandana, which Wamuu shreds with his wind. However, this is all parts of Joseph's plan, as both the oil from the bomb and the burning embers of Caesar's bandana are breathed in by Wamuu, causing him to explode from the inside. Deciding Wamuu's wounds from the Ripple are fatal, Joseph gives him some of his blood to ease his passing as a sign of respect, similar to the respect Wamuu showed Caesar. When the other vampires suddenly attack, Wamuu uses the last of his strength to kill them, not wanting them to interfere until the end. Upon Wamuu's request, Joseph drinks the antidote from his ring, allowing Wamuu to pass away with no regrets. It is soon time for Lisa Lisa's battle with Kars, with Lisa Lisa apparently getting the upper hand with her Ripple-infused scarf. However, Kars cheats by using a body double before stabbing Lisa Lisa from behind, showing no respect for the honor of battle unlike his compatriot, Wamuu. After claiming the Red Stone of Aja for himself, Kars sends his vampire army after the weakened JoJo. However, he is rescued by Stroheim and his men, along with Speedwagon and Smokey, who use ultraviolet lights to fight off the vampires whilst Joseph goes to face Kars. As Kars uses Lisa Lisa to force JoJo into a vulnerable position, Smokey reveals that Lisa Lisa is, in fact, Joseph's mother.",
		originalAirDate: "March 15, 2013",
		englishAirDate: "March 15, 2013",
		url: "https://www.crunchyroll.com/jojos-bizarre-adventure/episode-23-the-warrior-of-wind-652125",
	},
	{
		season: 2,
		episode: 15,
		title: "The Ties That Bind JoJo",
		titleJP: "JOJOを結ぶ絆",
		titleJPRomaji: "JoJo o Musubu Kizuna",
		description: "Being forced to cling onto a rope to stop Lisa Lisa from falling to her death, Joseph is at a huge disadvantage against Kars. He manages to trick Kars however using an elaborate snare and pushes into the crystals below. A flashback initiates revealing Lisa Lisa' pasts beginning with her meeting and marriage with Air Force Pilot, George Joestar II. It is also revealed that soon after Joseph's birth, George was murdered by a zombie who had presumably hidden away since the battle with Dio as an air force officer. When Elizabeth discovered the treachery, she hunted down the zombie and easily killed him with her Ripple powers, but she was caught in the act by an RAF official who thought she murdered a human in cold blood and burned the body to hide the evidence. Wanted throughout all of Europe, Elizabeth became a fugitive until she met with Speedwagon once more, using his foundation's resources to erase all traces of her past, and placing her on Venice's Air Supplena Island where she changed her name to Lisa Lisa. Back at the present, Stroheim attempts to finish off Kars with multiple blasts of ultraviolet beam, but Kars suddenly puts on the Stone Mask with the Red Stone of Aja in place. Before Stroheim can call off the attack, the artificial sunlight from all the German soldiers and Speedwagon Foundation operatives channels through the Super Aja, activating the Stone Mask and sending its undiluted energy into Kars, who undergoes a dramatic transformation.",
		originalAirDate: "March 22, 2013",
		englishAirDate: "March 22, 2013",
		url: "https://www.crunchyroll.com/jojos-bizarre-adventure/episode-24-the-ties-that-bind-jojo-652127",
	},
	{
		season: 2,
		episode: 16,
		title: "The Birth of a Superbeing",
		titleJP: "超生物の誕生!!",
		titleJPRomaji: "Chō Seibutsu no Tanjō!!",
		description: "Kars demonstrates his new powers, turning his hand into a flesh-eating squirrel that deals damage to Stroheim. The sun rises, killing the rest of the vampire minions, but Kars remains standing, immune thanks to the power of the stone. Joseph grabs the stone and runs off with Smokey to lure Kars away from the others whilst thinking of a plan. Leaving Smokey behind before he can tell him about Lisa Lisa, Joseph boards a plane to lure Kars away further. Joseph theorizes he may be able to beat Kars if he drops him into a volcano and heads towards a volcanic island of Italy. As Speedwagon attempts to stop Joseph by telling him about Lisa Lisa, the feathers that Kars had launched on JoJo's plane turn into piranhas, which cause the plane to ignite and start to dive into the island. Joseph uses his parachute to lure Kars into the path of the plane as it heads towards the volcano's crater. Kars attempts to escape, but Stroheim appears inside the plane and stops him. He rescues Joseph once the plane explodes by sacrificing his own robotic legs when they hit the ground. The volcano begins to erupt, and Kars is flung into the lava and begins to melt.",
		originalAirDate: "March 29, 2013",
		englishAirDate: "March 29, 2013",
		url: "https://www.crunchyroll.com/jojos-bizarre-adventure/episode-25-the-birth-of-a-superbeing-652129",
	},
	{
		season: 2,
		episode: 17,
		title: "The Ascendant One",
		titleJP: "神となった男",
		titleJPRomaji: "Kami to Natta Otoko",
		description: "Joseph's victory, along with his arm, is cut short when Kars manages to survive the volcano by forming a shield of air bubbles to protect him from its deadly lava. Joseph attempts to fight back but becomes shocked to discover that Kars has also learned how to use the Ripple, and at a potency one hundred times more powerful than JoJo's, causing his leg to start melting away. As Kars prepares to kill JoJo using his Ripple, JoJo subconsciously holds up the Red Stone of Aja just as Kars is about to strike, causing the island to erupt, launching both JoJo and Kars into the sky. Distracted by JoJo's severed arm hitting him, Kars is launched further into the sky by volcanic debris, pushing him outside of the Earth's gravitational pull. His body freezes, and with being unable to move and unable to die, Kars eventually stops thinking. It is now 1987. In New York's JFK Airport, a 67-year-old Joseph Joestar lashes out at a Japanese tourist after the man runs over his foot with a luggage cart, sorely upset that he has not seen his daughter in such a long since she married a Japanese man and moved to Tokyo. Four years earlier, a strange coffin is salvaged from the bottom of the Atlantic Ocean off the coast of the Canary Islands, engraved with the name \"DIO\". Back in the present in Tokyo, Jotaro Kujo sits in a jail cell.",
		originalAirDate: "April 5, 2013",
		englishAirDate: "April 5, 2013",
		url: "https://www.crunchyroll.com/jojos-bizarre-adventure/episode-26-the-ascendant-one-652131",
	},

];

export default Episodes;